name: Build & Publish

on:
  push:
    branches: [ "main" ]

jobs:
  build-backend:
    name: Build backend
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: nuget-

      - name: Restore dependencies
        run: dotnet restore VkPhotosExtractor.sln

      - name: Build
        run: dotnet build VkPhotosExtractor.sln --configuration Release --no-restore
    
  build-frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: ./VkPhotosExtractor.Frontend/node_modules
          key: npm-${{ hashFiles('VkPhotosExtractor.Frontend/package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        working-directory: ./VkPhotosExtractor.Frontend
        run: npm install

      - name: Build frontend
        working-directory: ./VkPhotosExtractor.Frontend
        run: npm run build
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: ./VkPhotosExtractor.Frontend/dist

  publish:
    name: Publish docker images
    needs: [ build-backend, build-frontend ]
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: ./VkPhotosExtractor.Frontend/dist

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create image tag
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Build & Push backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/tagiech/vk-photos-extractor:${{ env.SHORT_SHA }}
            
      - name: Build & Push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./VkPhotosExtractor.Frontend
          file: ./VkPhotosExtractor.Frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/tagiech/vk-photos-extractor-frontend:${{ env.SHORT_SHA }}
      
      - name: Add summary
        run: echo "Image tag:${{ env.SHORT_SHA }}" >> $GITHUB_STEP_SUMMARY

  cleanup-backend-packages:
    name: Cleanup old backend images
    needs: publish
    runs-on: ubuntu-latest

    permissions:
        packages: write

    steps:
      - name: Cleanup
        uses: actions/delete-package-versions@v4
        with:
          package-name: "vk-photos-extractor"
          package-type: "container"
          min-versions-to-keep: 5
          token: ${{ secrets.GITHUB_TOKEN }}
          
  cleanup-frontend-packages:
    name: Cleanup old frontend images
    needs: publish
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Cleanup
        uses: actions/delete-package-versions@v4
        with:
            package-name: "vk-photos-extractor-frontend"
            package-type: "container"
            min-versions-to-keep: 5
            token: ${{ secrets.GITHUB_TOKEN }}
